package com.example.todolist.ui.theme

import androidx.compose.ui.graphics.Color

//val md_theme_light_primary = Color(0xFF49680D)
//val md_theme_light_onPrimary = Color(0xFFFFFFFF)
//val md_theme_light_primaryContainer = Color(0xFFC9F087)
//val md_theme_light_onPrimaryContainer = Color(0xFF131F00)
//val md_theme_light_secondary = Color(0xFF596248)
//val md_theme_light_onSecondary = Color(0xFFFFFFFF)
//val md_theme_light_secondaryContainer = Color(0xFFDDE6C6)
//val md_theme_light_onSecondaryContainer = Color(0xFF171E0A)
//val md_theme_light_tertiary = Color(0xFF396661)
//val md_theme_light_onTertiary = Color(0xFFFFFFFF)
//val md_theme_light_tertiaryContainer = Color(0xFFBCECE5)
//val md_theme_light_onTertiaryContainer = Color(0xFF00201D)
//val md_theme_light_error = Color(0xFFBA1A1A)
//val md_theme_light_errorContainer = Color(0xFFFFDAD6)
//val md_theme_light_onError = Color(0xFFFFFFFF)
//val md_theme_light_onErrorContainer = Color(0xFF410002)
//val md_theme_light_background = Color(0xFFFEFCF4)
//val md_theme_light_onBackground = Color(0xFF1B1C18)
//val md_theme_light_surface = Color(0xFFFEFCF4)
//val md_theme_light_onSurface = Color(0xFF1B1C18)
//val md_theme_light_surfaceVariant = Color(0xFFE2E4D4)
//val md_theme_light_onSurfaceVariant = Color(0xFF45483D)
//val md_theme_light_outline = Color(0xFF75786C)
//val md_theme_light_inverseOnSurface = Color(0xFFF2F1E9)
//val md_theme_light_inverseSurface = Color(0xFF30312C)
//val md_theme_light_inversePrimary = Color(0xFFAED36E)
//val md_theme_light_shadow = Color(0xFF000000)
//val md_theme_light_surfaceTint = Color(0xFF49680D)
//val md_theme_light_outlineVariant = Color(0xFFC5C8B9)
//val md_theme_light_scrim = Color(0xFF000000)
//
//val seed = Color(0xFF49680D)