package com.example.todolist.ui.theme

import androidx.compose.ui.graphics.Color

//val md_theme_dark_primary = Color(0xFFAED36E)
//val md_theme_dark_onPrimary = Color(0xFF233600)
//val md_theme_dark_primaryContainer = Color(0xFF344E00)
//val md_theme_dark_onPrimaryContainer = Color(0xFFC9F087)
//val md_theme_dark_secondary = Color(0xFFC1CAAB)
//val md_theme_dark_onSecondary = Color(0xFF2B331D)
//val md_theme_dark_secondaryContainer = Color(0xFF414A32)
//val md_theme_dark_onSecondaryContainer = Color(0xFFDDE6C6)
//val md_theme_dark_tertiary = Color(0xFFA0D0C9)
//val md_theme_dark_onTertiary = Color(0xFF013733)
//val md_theme_dark_tertiaryContainer = Color(0xFF1F4E4A)
//val md_theme_dark_onTertiaryContainer = Color(0xFFBCECE5)
//val md_theme_dark_error = Color(0xFFFFB4AB)
//val md_theme_dark_errorContainer = Color(0xFF93000A)
//val md_theme_dark_onError = Color(0xFF690005)
//val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
//val md_theme_dark_background = Color(0xFF1B1C18)
//val md_theme_dark_onBackground = Color(0xFFE4E3DB)
//val md_theme_dark_surface = Color(0xFF1B1C18)
//val md_theme_dark_onSurface = Color(0xFFE4E3DB)
//val md_theme_dark_surfaceVariant = Color(0xFF45483D)
//val md_theme_dark_onSurfaceVariant = Color(0xFFC5C8B9)
//val md_theme_dark_outline = Color(0xFF8F9285)
//val md_theme_dark_inverseOnSurface = Color(0xFF1B1C18)
//val md_theme_dark_inverseSurface = Color(0xFFE4E3DB)
//val md_theme_dark_inversePrimary = Color(0xFF49680D)
//val md_theme_dark_shadow = Color(0xFF000000)
//val md_theme_dark_surfaceTint = Color(0xFFAED36E)
//val md_theme_dark_outlineVariant = Color(0xFF45483D)
//val md_theme_dark_scrim = Color(0xFF000000)
